# from github.com/almarklein/timetagger
version: "3.8"

services:
  timetagger:
    image: ghcr.io/almarklein/timetagger
    ports:
      - "80:80"
    volumes:
      - timetagger_db_volume:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
      - TIMETAGGER_CREDENTIALS=test:$$2a$$08$$0CD1NFiIbancwWsu3se1v.RNR/b7YeZd71yg3cZ/3whGlyU6Iny5i

volumes: # To be shared with timetagger-super-status
  timetagger_db_volume: # Volume key
    name: timetagger_shared_db_volume # Volume created with this name 
    